apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker-container
    image: docker
    command: ['cat']
    tty: true
    env:
    - name: REGISTRY
      value: registry.local
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  - name: kubectl-container
    image: gcr.io/cloud-builders/kubectl
    command: ['cat']
    tty: true
  - name: test-container
    image: node:16.10-alpine
    command: ['cat']
    tty: true
    resources: 
      requests:
        cpu: 100m
        memory: 256Mi
    env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "80"
    - name: PATH
      value: "/APP/bin:/APP/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  imagePullSecrets:
  - name: dockerhub
  nodeSelector:
    nodegroup-type: jenkins-nodes
  tolerations:
  - key: "jenkins-nodes"
    operator: "Exists"
    effect: "NoSchedule"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
